datasources:
  h2:
    url: jdbc:h2:mem:public;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver

kestra:
  server:
    basic-auth:
      enabled: false
  local-files:
    allowed-paths:
      - /files
  repository:
    type: h2
  queue:
    type: h2
  storage:
    type: local
    local:
      base-path: "/app/storage"
  tasks:
    tmp-dir:
      path: "/tmp/kestra-wd/tmp"
  url: "http://localhost:8080/"
